### PR TITLE
Feature/illumis data ingestion workflow

### PR DESCRIPTION
**Pull request by huystuhh**

### CODE REVIEW

**Comment by michaelefisher** [comment]
Nice! Did you find this straightforward once you got the object name settled?

**Review by michaelefisher — APPROVED** [review]
Is this deployed in our prod?

**Comment by huystuhh** [comment]
@michaelefisher yeah, once I got the hang of workflows anyways. I feel like there's always a somewhat steep baseline knowledge you need working with a new service on Google due to their documentation but once I got my feet wet looking around things for a while it wasn't too difficult.

**Comment by huystuhh** [comment]
@michaelefisher also yes, it's deployed in our prod currently.

**Pull request merged**
